version: "3.8"
services:
    web:
      image: devopstrainer/java-mvn-privaterepos:php8
      ports:
      - "8001:80"
      deploy:
          replicas: 2
      depends_on:
      - mysql
    mysql:
      image: devopstrainer/java-mvn-privaterepos:mysql
      volumes:
      - db_data:/var/lib/mysql
      environment:
        MYSQL_ROOT_PASSWORD: password
        MYSQL_DATABASE: mydatabase
volumes:
   db_data: {}
